# Generated by Django 5.0.1 on 2024-01-24 18:49

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="todo",
            name="tag",
            field=models.ManyToManyField(to="todo.tag"),
        ),
    ]
