# Generated by Django 5.0.1 on 2024-01-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="todo.category",
            ),
        ),
    ]
