# Generated by Django 5.0.1 on 2024-01-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_todo_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
