# Generated by Django 5.0.1 on 2024-01-22 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_category_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="cerated_at",
            new_name="created_at",
        ),
    ]
